version: '3'
services:
  # service_name:
  #   container_name: container_name
  #   image: image
  #   env_file:
  #     - env_file
  #   environment:
  #     - name=value
  #   ports:
  #     - 'external:internal'
  #   volumes:
  #     - hostPath:containerPath:ro
  #   command: override default command
  #   depends_on:
  #     - run after specified services

  postgres_db:
    container_name: postgres_db
    image: postgres:14.1
    environment:
      - POSTGRES_USER=foo
      - POSTGRES_PASSWORD=foobarbaz
      - POSTGRES_DB=madworld_db
    ports:
      - '3300:5432'
    volumes:
      - .db:/docker-entrypoint-initdb.d/
      - .db_data:/var/lib/postgresql/data

  minio_storage:
    container_name: minio_storage
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: localminio
      MINIO_ROOT_PASSWORD: localminiopassword
    volumes:
      - .minio_storage:/data

  mysql_db:
    container_name: mysql_db
    image: mysql:8.0
    ports:
      - "3306:3306"
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - .data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=secret

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - .rabbitmq/data/:/var/lib/rabbitmq/
        - .rabbitmq/log/:/var/log/rabbitmq

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - '6978:6379'